<?php

namespace Rgbcode_authform\classes\plugins;

use Rgbcode_authform\classes\helpers\Location;
use Rgbcode_authform\traits\Singleton;

class ACF {

	use Singleton;

	public function __construct() {
		//      https://www.advancedcustomfields.com/resources/options-page/
		add_action( 'init', [ $this, 'register_options_page' ] );

		//      in this hook you need register your fields
		//      https://www.advancedcustomfields.com/resources/register-fields-via-php/
		add_action( 'init', [ $this, 'register_fields' ] );
		add_filter( 'acf/load_field/key=field_5f5e31d44f719', [ $this, 'get_list_countries' ] );
		add_filter( 'acf/load_field/key=field_5f5e31d44f819', [ $this, 'get_list_currencies' ] );
		add_filter( 'acf/load_value/key=field_5f5e3263d8k8o', [ $this, 'get_default_suggestions' ], 10, 3 );
	}

	public function register_options_page() {

		if ( function_exists( 'acf_add_options_page' ) ) {
			acf_add_options_page(
				[
					'page_title' => esc_attr__( 'Authform', 'rgbcode-authform' ),
					'menu_title' => esc_attr__( 'Authform', 'rgbcode-authform' ),
					'menu_slug'  => 'rgbcode-authform-options',
					'capability' => 'edit_posts',
					'icon_url'   => 'dashicons-forms', // Add this line and replace the second inverted commas with class of the icon you like
					'position'   => 30,
					'redirect'   => false,
				]
			);
		}
	}

	public function register_fields() {
		if ( function_exists( 'acf_add_local_field_group' ) ) :

			acf_add_local_field_group(
				array(
					'key'                   => 'group_62f20424bf6b0',
					'title'                 => esc_attr__( 'Authform settings', 'rgbcode-authform' ),
					'fields'                => array(
						array(
							'key'               => 'field_630b0fb1d97ad',
							'label'             => esc_attr__( 'Enable forms', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_enable',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'ui'                => 1,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
						// General
						array(
							'key'               => 'field_630b1083f77ae',
							'label'             => esc_attr__( 'General', 'rgbcode-authform' ),
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_630b0fb1d97ad',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_62fb555a5a210',
							'label'             => esc_attr__( 'Language', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_lang',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'en' => 'English',
								'ar' => 'Arabish',
								'es' => 'Spanish',
							),
							'default_value'     => 'en',
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_649844f7714a9',
							'label'             => esc_attr__( 'Logo', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_logo',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						// Login
						array(
							'key'               => 'field_630b1083dgt67',
							'label'             => esc_attr__( 'Login', 'rgbcode-authform' ),
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_630b0fb1d97ad',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_62f20e356fgh7',
							'label'             => esc_attr__( 'Email', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_login_email',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20e9f6bgb4',
									'label'             => esc_attr__( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Email', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f20ed86bsa2',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please insert a valid email address', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f20fdffr472',
							'label'             => esc_attr__( 'Password', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_login_pass',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20fdfdddf5',
									'label'             => esc_attr__( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Password', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62ff45dffngj8',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Must be at least minimum 6 characters', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f210ec26gh7',
							'label'             => esc_attr__( 'Submit button', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_login_submit',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => esc_attr__( 'Login', 'rgbcode-authform' ),
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62f20e356dcc',
							'label'             => esc_attr__( 'Bottom Login Link', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_login_link',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f2h7ui26gh7',
									'label'             => esc_attr__( 'First Text', 'rgbcode-authform' ),
									'name'              => 'first_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Don’t have account yet?', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f2h7ui26mk9',
									'label'             => esc_attr__( 'Link text', 'rgbcode-authform' ),
									'name'              => 'link_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Start today', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						// Sign Up
						array(
							'key'               => 'field_630b1083d97ae',
							'label'             => esc_attr__( 'Sign Up', 'rgbcode-authform' ),
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_630b0fb1d97ad',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_62f2122c05b9b',
							'label'             => esc_attr__( 'Title block', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_title_block',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f2125d05b9c',
									'label'             => esc_attr__( 'Title', 'rgbcode-authform' ),
									'name'              => 'title',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Sign up and Start Trading', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f2128205b9d',
									'label'             => esc_attr__( 'Subtitle', 'rgbcode-authform' ),
									'name'              => 'subtitle',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please fill in your details below', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6bdce',
							'label'             => esc_attr__( 'First Name', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_first_name',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dce6bdcf',
									'label'             => esc_attr__( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'First name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62f20df76bdd0',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please insert a valid first name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6bdcz',
							'label'             => esc_attr__( 'Last Name', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_last_name',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dce6bdcx',
									'label'             => esc_attr__( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Last name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62f20df76bdd6',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please insert a valid last name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f20e356bdd1',
							'label'             => esc_attr__( 'Email', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_email',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20e9f6bdd2',
									'label'             => esc_attr__( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Email', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f20ed86bdd3',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please insert a valid email address', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'                 => 'field_5f5e3263d8k8o',
									'label'               => esc_attr__( 'Suggestions', 'rgbcode-authform' ),
									'name'                => 'suggestions',
									'type'                => 'repeater',
									'instructions'        => '',
									'required'            => 0,
									'conditional_logic'   => 0,
									'wrapper'             => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'wpml_cf_preferences' => 1,
									'collapsed'           => '',
									'min'                 => 0,
									'max'                 => 0,
									'layout'              => 'table',
									'button_label'        => esc_attr__( 'Add suggestion', 'rgbcode-authform' ),
									'sub_fields'          => array(
										array(
											'key'          => 'field_62f20fbaddg5v',
											'label'        => esc_attr__( 'Suggestion', 'rgbcode-authform' ),
											'name'         => 'suggestion',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
									),
								),
							),
						),
						array(
							'key'               => 'field_62f20fbadda6e',
							'label'             => esc_attr__( 'Phone', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_phone',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20fbadda6f',
									'label'             => esc_attr__( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Phone', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f20fbadda70',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please insert a valid phone number', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f20fdfdda72',
							'label'             => esc_attr__( 'Password', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_pass',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20fdfdda73',
									'label'             => esc_attr__( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Password', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f20fdfdda74',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Must be at least 6 characters Use characters and numbers only', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2108469f72',
							'label'             => esc_attr__( 'Terms and Conditions', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_terms',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'tabs'              => 'all',
							'toolbar'           => 'basic',
							'media_upload'      => 0,
							'delay'             => 0,
						),
						array(
							'key'               => 'field_62f210ec26e88',
							'label'             => esc_attr__( 'Submit button', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_submit',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => esc_attr__( 'Submit', 'rgbcode-authform' ),
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62f2114826e89',
							'label'             => esc_attr__( 'Message under the button', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_message',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => esc_attr__( 'CFD and Forex trading involves substantial risk and may result in the loss of the invested capital.', 'rgbcode-authform' ),
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62f211b426e8a',
							'label'             => esc_attr__( 'Link', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_link',
							'type'              => 'link',
							'instructions'      => esc_attr__( 'Link at the bottom of the form', 'rgbcode-authform' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						// Deposit
						array(
							'key'               => 'field_630b1083d97as',
							'label'             => esc_attr__( 'Deposit', 'rgbcode-authform' ),
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_630b0fb1d97ad',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_62f2122c05b9q',
							'label'             => esc_attr__( 'Title block', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_title_block',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f2125d05b9w',
									'label'             => esc_attr__( 'Title', 'rgbcode-authform' ),
									'name'              => 'title',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Thank you for signing-up!', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f2128805b9d',
									'label'             => esc_attr__( 'Subtitle', 'rgbcode-authform' ),
									'name'              => 'subtitle',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please complete your registration in order to proceed with a deposit and start trading', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2125d05b9e',
							'label'             => esc_attr__( 'Label for country field', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_country',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => esc_attr__( 'Country', 'rgbcode-authform' ),
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62f2043d6bxoO',
							'label'             => esc_attr__( 'Currency', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_currency',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dcu6baeG',
									'label'             => esc_attr__( 'Label', 'rgbcode-authform' ),
									'name'              => 'label',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Currency', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62f28df76bXe4',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Choose currency', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6buce',
							'label'             => esc_attr__( 'City', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_city',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dcu6bdcf',
									'label'             => esc_attr__( 'Label', 'rgbcode-authform' ),
									'name'              => 'label',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'City', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62f28df76bdd0',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please insert a valid city name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6muce',
							'label'             => esc_attr__( 'Address', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_address',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dcu9bdcf',
									'label'             => esc_attr__( 'Label', 'rgbcode-authform' ),
									'name'              => 'label',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Address', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62f20df96bdd0',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please insert a valid address', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6iuce',
							'label'             => esc_attr__( 'Zip code(postcode)', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_postcode',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dcn6bdcf',
									'label'             => esc_attr__( 'Label', 'rgbcode-authform' ),
									'name'              => 'label',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Zip code / Postcode', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_52f20df76bdd0',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Please insert a valid Zip code', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6iucs',
							'label'             => esc_attr__( 'Date of Birth', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_birthday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62i20dcn6bdcf',
									'label'             => esc_attr__( 'Label', 'rgbcode-authform' ),
									'name'              => 'label',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Date of Birth', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62i20dcn6bzio',
									'label'             => esc_attr__( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Choose date', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_52f20df76odd0',
									'label'             => esc_attr__( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Must be over 18+', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6iuds',
							'label'             => esc_attr__( 'WhatsApp button', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_whatsapp',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62ithdcn6bdcf',
									'label'             => esc_attr__( 'Button text', 'rgbcode-authform' ),
									'name'              => 'button_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'Whatsapp Us', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_649356e8bf2a6',
									'label'             => esc_attr__( 'Background color', 'rgbcode-authform' ),
									'name'              => 'whatsapp_btn_back_color',
									'type'              => 'color_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '#128c7e',
									'enable_opacity'    => 0,
									'return_format'     => 'string',
								),
								array(
									'key'               => 'field_649356e8bf2r5',
									'label'             => esc_attr__( 'Text color', 'rgbcode-authform' ),
									'name'              => 'whatsapp_btn_txt_color',
									'type'              => 'color_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '#ffffff',
									'enable_opacity'    => 0,
									'return_format'     => 'string',
								),
								array(
									'key'               => 'field_52f20df76hdr0',
									'label'             => esc_attr__( 'Phone number', 'rgbcode-authform' ),
									'name'              => 'phone_number',
									'type'              => 'number',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_52f20df76hdd6',
									'label'             => esc_attr__( 'Whatsapp text', 'rgbcode-authform' ),
									'name'              => 'whatsapp_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'I need help opening my account', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f210ec26e38',
							'label'             => esc_attr__( 'Submit button', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_submit',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => esc_attr__( 'Next', 'rgbcode-authform' ),
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_630b1083d97re',
							'label'             => esc_attr__( 'Currencies', 'rgbcode-authform' ),
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_630b0fb1d97ad',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'                 => 'field_5f5e3263d83e5',
							'label'               => esc_attr__( 'Country currencies', 'rgbcode-authform' ),
							'name'                => 'rgbc_authform_currencies',
							'type'                => 'repeater',
							'instructions'        => '',
							'required'            => 0,
							'conditional_logic'   => 0,
							'wrapper'             => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'wpml_cf_preferences' => 1,
							'collapsed'           => '',
							'min'                 => 0,
							'max'                 => 0,
							'layout'              => 'table',
							'button_label'        => '',
							'sub_fields'          => array(
								array(
									'key'                 => 'field_5f5e31d44f719',
									'label'               => esc_attr__( 'Country', 'rgbcode-authform' ),
									'name'                => 'country',
									'type'                => 'select',
									'instructions'        => '',
									'required'            => 0,
									'conditional_logic'   => 0,
									'wrapper'             => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'             => array(),
									'default_value'       => false,
									'wpml_cf_preferences' => 1,
									'allow_null'          => 0,
									'multiple'            => 0,
									'ui'                  => 0,
									'return_format'       => 'value',
									'ajax'                => 0,
									'placeholder'         => '',
								),
								array(
									'key'                 => 'field_5f5e31d44f819',
									'label'               => esc_attr__( 'Currencies', 'rgbcode-authform' ),
									'name'                => 'currencies',
									'type'                => 'select',
									'instructions'        => '',
									'required'            => 0,
									'conditional_logic'   => 0,
									'wrapper'             => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'             => array(),
									'default_value'       => Location::DEFAULT_CURRENCIES,
									'wpml_cf_preferences' => 1,
									'allow_null'          => 0,
									'multiple'            => 1,
									'ui'                  => 1,
									'return_format'       => 'value',
									'ajax'                => 0,
									'placeholder'         => '',
								),
								array(
									'key'               => 'field_630b0fb1d97zb',
									'label'             => esc_attr__( 'Add empty option', 'rgbcode-authform' ),
									'name'              => 'is_empty_value',
									'type'              => 'true_false',
									'instructions'      => esc_attr__( 'Add an empty default value to oblige the client to choose a currency', 'rgbcode-authform' ),
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'message'           => '',
									'default_value'     => 0,
									'ui'                => 1,
									'ui_on_text'        => '',
									'ui_off_text'       => '',
								),
							),
						),
						array(
							'key'               => 'field_62f210ec26e56',
							'label'             => esc_attr__( 'Empty option text', 'rgbcode-authform' ),
							'name'              => 'empty_option_txt',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => esc_attr__( 'Please select', 'rgbcode-authform' ),
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
					'location'              => array(
						array(
							array(
								'param'    => 'options_page',
								'operator' => '==',
								'value'    => 'rgbcode-authform-options',
							),
						),
					),
					'menu_order'            => 0,
					'position'              => 'normal',
					'style'                 => 'default',
					'label_placement'       => 'top',
					'instruction_placement' => 'label',
					'hide_on_screen'        => '',
					'active'                => true,
					'description'           => '',
					'show_in_rest'          => 0,
				)
			);

		endif;
		// phpcs:enable
	}

	public function get_list_countries( $field ): array {
		$field['choices'] = [];

		foreach ( Location::COUNTRIES as $country ) {
			$field['choices'][ $country['name'] ] = $country['name'];
		}

		// return the field
		return $field;
	}

	public function get_list_currencies( $field ): array {
		$field['choices'] = [];

		foreach ( Location::CURRENCIES as $code => $country ) {
			$field['choices'][ $code ] = "$code ($country)";
		}

		// return the field
		return $field;
	}

	public function get_default_suggestions( $value, $post_id, $field ) {

		if ( $value === false ) {

			return [
				[
					'field_62f20fbaddg5v' => 'gmail.com',
				],
				[
					'field_62f20fbaddg5v' => 'hotmail.com',
				],
				[
					'field_62f20fbaddg5v' => 'outlook.com',
				],
				[
					'field_62f20fbaddg5v' => 'yahoo.com',
				],
				[
					'field_62f20fbaddg5v' => 'skype.com',
				],
			];
		}

		return $value;
	}
}
