<?php

namespace Rgbcode_authform\classes\plugins;

use Rgbcode_authform\traits\Singleton;

class ACF {

	use Singleton;

	public function __construct() {
		//      https://www.advancedcustomfields.com/resources/options-page/
		add_action( 'init', [ $this, 'register_options_page' ] );

		//      in this hook you need register your fields
		//      https://www.advancedcustomfields.com/resources/register-fields-via-php/
		add_action( 'init', [ $this, 'register_fields' ] );
	}

	public function register_options_page() {

		if ( function_exists( 'acf_add_options_page' ) ) {
			acf_add_options_page(
				[
					'page_title' => __( 'Authform', 'rgbcode-authform' ),
					'menu_title' => __( 'Authform', 'rgbcode-authform' ),
					'menu_slug'  => 'rgbcode-authform-options',
					'capability' => 'edit_posts',
					'icon_url'   => 'dashicons-forms', // Add this line and replace the second inverted commas with class of the icon you like
					'position'   => 30,
					'redirect'   => false,
				]
			);
		}
	}

	public function register_fields() {
		if ( function_exists( 'acf_add_local_field_group' ) ) :

			acf_add_local_field_group(
				array(
					'key'                   => 'group_62f20424bf6b0',
					'title'                 => __( 'Authform settings', 'rgbcode-authform' ),
					'fields'                => array(
						array(
							'key'               => 'field_630b0fb1d97ad',
							'label'             => __( 'Enable forms', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_enable',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'ui'                => 1,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
						array(
							'key'               => 'field_630b1083d97ae',
							'label'             => __( 'Sign Up', 'rgbcode-authform' ),
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_630b0fb1d97ad',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_62fb555a5a210',
							'label'             => __( 'Language', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_lang',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'en' => 'English',
								'ar' => 'Arabish',
								'es' => 'Spanish',
							),
							'default_value'     => 'en',
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_62f2122c05b9b',
							'label'             => __( 'Title block', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_title_block',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f2125d05b9c',
									'label'             => __( 'Title', 'rgbcode-authform' ),
									'name'              => 'title',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Sign up and Start Trading', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f2128205b9d',
									'label'             => __( 'Subtitle', 'rgbcode-authform' ),
									'name'              => 'subtitle',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Please fill in your details below', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6bdce',
							'label'             => __( 'First Name', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_first_name',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dce6bdcf',
									'label'             => __( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'First name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62f20df76bdd0',
									'label'             => __( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Please insert a valid first name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6bdcz',
							'label'             => __( 'Last Name', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_last_name',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dce6bdcx',
									'label'             => __( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Last name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62f20df76bdd6',
									'label'             => __( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Please insert a valid last name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f20e356bdd1',
							'label'             => __( 'Email', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_email',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20e9f6bdd2',
									'label'             => __( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Email', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f20ed86bdd3',
									'label'             => __( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Please insert a valid email address', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f20fbadda6e',
							'label'             => __( 'Phone', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_phone',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20fbadda6f',
									'label'             => __( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Phone', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f20fbadda70',
									'label'             => __( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Please insert a valid phone number', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f20fdfdda72',
							'label'             => __( 'Password', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_pass',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20fdfdda73',
									'label'             => __( 'Placeholder', 'rgbcode-authform' ),
									'name'              => 'placeholder',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Password', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f20fdfdda74',
									'label'             => __( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Must be at least 6 characters Use characters and numbers only', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2108469f72',
							'label'             => __( 'Terms and Conditions', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_terms',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'tabs'              => 'all',
							'toolbar'           => 'basic',
							'media_upload'      => 0,
							'delay'             => 0,
						),
						array(
							'key'               => 'field_62f210ec26e88',
							'label'             => __( 'Submit button', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_submit',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Submit',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62f2114826e89',
							'label'             => __( 'Message under the button', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_message',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => __( 'CFD and Forex trading involves substantial risk and may result in the loss of the invested capital.', 'rgbcode-authform' ),
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62f211b426e8a',
							'label'             => __( 'Link', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_link',
							'type'              => 'link',
							'instructions'      => __( 'Link at the bottom of the form', 'rgbcode-authform' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						array(
							'key'               => 'field_630b1083d97as',
							'label'             => __( 'Deposit', 'rgbcode-authform' ),
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_630b0fb1d97ad',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_62f2122c05b9q',
							'label'             => __( 'Title block', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_title_block',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f2125d05b9w',
									'label'             => __( 'Title', 'rgbcode-authform' ),
									'name'              => 'title',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Thank you for signing-up!', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_62f2128805b9d',
									'label'             => __( 'Subtitle', 'rgbcode-authform' ),
									'name'              => 'subtitle',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Please complete your registration in order to proceed with a deposit and start trading', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2125d05b9e',
							'label'             => __( 'Label for country field', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_country',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => __( 'Country', 'rgbcode-authform' ),
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62f2043d6buce',
							'label'             => __( 'City', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_city',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dcu6bdcf',
									'label'             => __( 'Label', 'rgbcode-authform' ),
									'name'              => 'label',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'City', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62f28df76bdd0',
									'label'             => __( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Please insert a valid city name', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6muce',
							'label'             => __( 'Address', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_address',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dcu9bdcf',
									'label'             => __( 'Label', 'rgbcode-authform' ),
									'name'              => 'label',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Address', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_62f20df96bdd0',
									'label'             => __( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Please insert a valid address', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6iuce',
							'label'             => __( 'Zip code(postcode)', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_postcode',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62f20dcn6bdcf',
									'label'             => __( 'Label', 'rgbcode-authform' ),
									'name'              => 'label',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Zip code / Postcode', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_52f20df76bdd0',
									'label'             => __( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Please insert a valid Zip code', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f2043d6iucs',
							'label'             => __( 'Date of Birth', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_birthday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62i20dcn6bdcf',
									'label'             => __( 'Label', 'rgbcode-authform' ),
									'name'              => 'label',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Date of Birth', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_52f20df76odd0',
									'label'             => __( 'Error text', 'rgbcode-authform' ),
									'name'              => 'error_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => __( 'Must be over 18+', 'rgbcode-authform' ),
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_62f210ec26e38',
							'label'             => __( 'Submit button', 'rgbcode-authform' ),
							'name'              => 'rgbc_authform_deposit_submit',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => __( 'Next', 'rgbcode-authform' ),
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
					'location'              => array(
						array(
							array(
								'param'    => 'options_page',
								'operator' => '==',
								'value'    => 'rgbcode-authform-options',
							),
						),
					),
					'menu_order'            => 0,
					'position'              => 'normal',
					'style'                 => 'default',
					'label_placement'       => 'top',
					'instruction_placement' => 'label',
					'hide_on_screen'        => '',
					'active'                => true,
					'description'           => '',
					'show_in_rest'          => 0,
				)
			);

		endif;
		// phpcs:enable
	}
}
